### ISSUE TITLE
I could not draw concave in teleport Area by spline.

### ISSUE THREAD

**Issue by wxx0136** [mitchemmc/VRContentExamples#3] opened 2016-07-27 09:24 UTC
Hi, mitchemmc. Thank you for your plug-in. It's very helpful. But there is a problem that I can't solve.
**I could not draw concave in teleport Area by spline**. Could you help me. THX

**Comment by mitchemmc** [comment] 2016-07-27 09:39
I'm not sure what you mean by could not draw concave? The initial setup in the project is concave, how is it different? maybe a picture could help

**Comment by swing1005** [comment] 2016-07-28 01:56
Hi, mitchemmc, I changed a another ID . The difference is shown in the following figure.
[picture1](https://github.com/swing1005/UE4/blob/master/_20160727180048.jpg)
[picture2](https://github.com/swing1005/UE4/blob/master/_20160727180056.png)

**Comment by wxx0136** [comment] 2016-08-01 08:26
hi, @mitchemmc. I am updating my problem with pics.
[my problem](https://github.com/swing1005/UE4/blob/master/_20160727180048.jpg)
[original pic ](https://github.com/swing1005/UE4/blob/master/_20160727180056.png)
waiting for you repeat. thx

**Comment by mitchemmc** [comment] 2016-08-17 08:13
Sorry for the late reply the issue is now fixed in the 4.13 test build

**Closed as completed by mitchemmc** 2016-08-17 08:13 UTC
